#!/usr/bin/env zsh
#
# My lemonbar setup.
# IMPORTANT:  This configuration is only compatible with
#             a lemonbar fork with xft font compatibility.
#
BAR_HEIGHT_RATIO=04


# Find BSPWM gap ratio
BSPWM_GAP=$(cat $HOME/.config/bspwm/bspwmrc | awk '/window_gap/{print $4}')
if [[ $(echo $BSPWM_GAP | wc -l) -gt 1 ]]; then BSPWM_GAP=0$BSPWM_GAP; fi

MONITOR_WIDTH=$(xrandr --query |awk -F '[ x+]' '/\<connected\>/{print $4}')
MONITOR_HEIGHT=$(xrandr --query |awk -F '[ x+]' '/\<connected\>/{print $5}')
BAR_WIDTH=$(echo "$MONITOR_WIDTH - $((BSPWM_GAP * 2))" | bc -l | sed 's/\..*//')
BAR_HEIGHT=$(echo "$MONITOR_HEIGHT * .$BAR_HEIGHT_RATIO" | bc -l | sed 's/\..*//')

CHARGING_INDEX=1

is_charging() {
    if cat /sys/class/power_supply/BAT0/status | grep Discharging &>/dev/null; then
        return 1
    else
        return 0
    fi
}

bar_date() {
    date '+%I:%M %p' | sed 's/^0//'
}

bar_battery() {
    local charge_array=('' '' '' '' '')
    local glyph
    local charge=$(cat /sys/class/power_supply/BAT0/capacity)

    if ! is_charging; then
        if [[ $charge < 15 ]]; then
            glyph=${charge_array[1]}
        elif [[ $charge < 40 ]]; then
            glyph=${charge_array[2]}
        elif [[ $charge < 70 ]]; then
            glyph=${charge_array[3]}
        elif [[ $charge < 90 ]]; then
            glyph=${charge_array[4]}
        else
            glyph=${charge_array[5]}
        fi
    else
        glyph=${charge_array[$CHARGING_INDEX]}
    fi

    echo -e "$glyph $charge%"
}

bar_active_nodes() {
    local current_window
    local tmp
    for i in {2..11}; do
        tmp=$(bspc wm --get-status | awk -F':' -v i="$i" '{print $i}')
        if [[ $tmp =~ ^O || $tmp =~ ^F ]]; then
            current_window=$((i-1))
        fi
    done
    echo $current_window
}

while :; do
    UPTIME=$(cat /proc/uptime | awk -F'.' '{print $1}')
    if [[ $RAN = true ]]; then
        REFRESH=false
    fi
    if [[ $((UPTIME % 5)) != 0 ]]; then
        RAN=false
        REFRESH=false
    elif [[ $RAN != true ]]; then
        REFRESH=true
        RAN=true
    fi
    if [[ $REFRESH = true || -z "$TIME" ]]; then
        TIME=$(bar_date)
    fi
    if [[ $REFRESH = true || -z "$BATTERY" ]]; then
        BATTERY=$(bar_battery)
        if is_charging; then
            if [[ $CHARGING_INDEX = 5 ]]; then
                CHARGING_INDEX=1
            else
                CHARGING_INDEX=$((CHARGING_INDEX + 1))
            fi
        fi
    fi
    echo " %{l}$(bar_active_nodes)%{c}$TIME%{r}$BATTERY "
done | lemonbar \
            -o -1 \
            -f '-misc-font awesome 5 free solid-black-r-normal--0-0-0-0-p-0-iso10646-1' \
            -o 1 \
            -f 'Noto Sans Medium-11' \
            -g "$BAR_WIDTH"x"$BAR_HEIGHT"+"$BSPWM_GAP"+"$((BSPWM_GAP / 2))" \
            -B '#141b35' \
            -p
