#!/usr/bin/env zsh
set -x

SCRIPT=$(realpath $0)
exec 6< $SCRIPT
flock -n 6 || exit

BRIGHTNESS_STEPS=15
MINIMUM_BRIGHTNESS=1
BRIGHTNESS=$(printf "%.0f\n" $(light))

set_brightness() {
    for steps in $(seq $1); do
        [[ $BRIGHTNESS = 100 && $2 != - ]] && break
        light -S $((BRIGHTNESS $2 1))
        sleep .002
        BRIGHTNESS=$((BRIGHTNESS $2 1))
    done
}

if [[ $1 = -inc ]]; then
    if [[ $BRIGHTNESS -le 10 ]]; then
        set_brightness 1 +
    else
        set_brightness $BRIGHTNESS_STEPS +
    fi
elif [[ $1 = -dec && $BRIGHTNESS -gt $((MINIMUM_BRIGHTNESS + BRIGHTNESS_STEPS)) ]]; then
    set_brightness $BRIGHTNESS_STEPS -
elif [[ -n $1 ]]; then
    if [[ $BRIGHTNESS -gt $MINIMUM_BRIGHTNESS ]]; then
        if [[ $BRIGHTNESS -le 10 ]]; then
            set_brightness 1 -
        else
            set_brightness $((BRIGHTNESS - MINIMUM_BRIGHTNESS)) -
        fi
    fi
fi

printf '%s' "$BRIGHTNESS" > $HOME/.cache/brightness/percentage
