#!/usr/bin/env zsh

SCRIPT=$(realpath $0)
exec 6< $SCRIPT
flock -n 6 || exit

BRIGHTNESS_STEPS=15
MINIMUM_BRIGHTNESS=1
BRIGHTNESS=$(printf "%.0f\n" $(light))

set_brightness() {
    for steps in $(seq $1); do
        [[ $BRIGHTNESS = 100 && $2 != - ]] && break
        light -S $((BRIGHTNESS $2 1))
        sleep .002
        BRIGHTNESS=$((BRIGHTNESS $2 1))
    done
}

if [[ $1 = -inc ]]; then
    if [[ $BRIGHTNESS -le 10 ]]; then
        set_brightness 1 +
    else
        set_brightness $BRIGHTNESS_STEPS +
    fi
elif [[ $1 = -dec && $BRIGHTNESS -gt $((MINIMUM_BRIGHTNESS + BRIGHTNESS_STEPS)) ]]; then
    set_brightness $BRIGHTNESS_STEPS -
elif [[ -n $1 ]]; then
    if [[ $BRIGHTNESS -gt $MINIMUM_BRIGHTNESS ]]; then
        if [[ $BRIGHTNESS -le 10 ]]; then
            set_brightness 1 -
        else
            set_brightness $((BRIGHTNESS - MINIMUM_BRIGHTNESS)) -
        fi
    fi
fi

if [[ $BRIGHTNESS = 100 ]]; then
    BRIGHTNESS=Max
elif [[ $BRIGHTNESS = $MINIMUM_BRIGHTNESS ]]; then
    BRIGHTNESS="Min ($MINIMUM_BRIGHTNESS)"
else
    PERCENT=%
fi

BRIGHTNESS_ICON=$(printf "%.0f\n" $(echo "$((100 + MINIMUM_BRIGHTNESS)) * .5" | bc -l))

if [[ $BRIGHTNESS = Max ]]; then
    ICON=full
elif [[ $BRIGHTNESS =~ Min ]]; then
    ICON=off
elif [[ $BRIGHTNESS -ge $BRIGHTNESS_ICON ]]; then
    ICON=medium
elif [[ $BRIGHTNESS -lt $BRIGHTNESS_ICON ]]; then
    ICON=low
fi

notify-send.sh --icon=/usr/share/icons/Numix/48/notifications/notification-display-brightness-$ICON.svg \
        -R /tmp/brightness_notifyd_id "$BRIGHTNESS$PERCENT" -t 1000
