#!/usr/bin/env bash

. build/envsetup.sh
tg_bot "Starting BootleggersROM build for sailfish $1"
elapsed
if ! brunch sailfish; then
    err "Bootleggers build failed!"
    tg_bot "BootleggersROM build for sailfish failed, @shagbag913"
    return 1
fi
(
    cd out/target/product/sailfish
    cp $(ls BootleggersROM*.zip | sort | tail -n 1) /android/gdrive/Public/Bootleggers
)
if grive -p /android/gdrive; then
    ELAPSED_TIME=$(elapsed)
    tg_bot "BootleggersROM build for sailfish successful! Built and uploaded in $ELAPSED_TIME."
fi
