#!/usr/bin/env zsh

if [[ -f $HOME/.cache/custom_dmenu ]]; then
    . $HOME/.cache/custom_dmenu
else
    # Vertical size in percentage, must match lemonbar_wrapper value!
    BAR_HEIGHT_RATIO=04

    XRANDR_QUERY=$(xrandr --query)

    MONITOR_WIDTH=$(echo $XRANDR_QUERY | grep ' connected' | grep -o '[0-9][0-9]\+' | sed -n 1p)
    MONITOR_HEIGHT=$(echo $XRANDR_QUERY | grep ' connected' | grep -o '[0-9][0-9]\+' | sed -n 2p)
    BSPWM_GAP=$(awk '/window_gap/{print $4}' $HOME/.config/bspwm/bspwmrc)
    DMENU_WIDTH=$(echo "$MONITOR_WIDTH - $BSPWM_GAP * 2" | bc -l | sed 's/\..*//')
    DMENU_HEIGHT=$(echo "$MONITOR_HEIGHT * .$BAR_HEIGHT_RATIO" | bc -l | sed 's/\..*//')
    DMENU_Y=$((MONITOR_HEIGHT - DMENU_HEIGHT - (BSPWM_GAP / 2)))

    # Cache
    for var in BSPWM_GAP DMENU_Y DMENU_WIDTH DMENU_HEIGHT; do
        val=$(eval "echo \${$var}")
        echo "$var=$val" >> $HOME/.cache/custom_dmenu
    done
fi

# Hide lemonbar so we can overlap it with proper transparency
LEMONBAR_WID=$(xdo id -n lemonbar)
if [[ -n "$LEMONBAR_WID" ]]; then
    xdo hide "$LEMONBAR_WID"
fi

dmenu_run -fn 'Google Sans Medium-13' -x $BSPWM_GAP -y $DMENU_Y -w $DMENU_WIDTH -h $DMENU_HEIGHT \
        -nb '#1c1a2b' -nf "$COLOR_FOREGROUND" -sb '#1c1a2b' -o .95

until ! ps -e | grep -q dmenu; do
    :
done

if [[ -n "$LEMONBAR_WID" ]]; then
    xdo show "$LEMONBAR_WID"
fi
