#!/usr/bin/env bash
#
# Upload input text to del.dog and output a link

RESULT=$(curl -sf --data-binary "$1" https://del.dog/documents) || {
    echo "ERROR: failed to post document" >&2
    exit 1
}

KEY=$(jq -r .key <<< "$RESULT")
echo "https://del.dog/$KEY"
