#!/usr/bin/env zsh
#
# Tool to generate commented apache license for various languages
#

__gen_apache() {
cat << EOF
Copyright (C) $(date +%Y) $1

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
EOF
}

if [[ "$2" = 'xml' ]]; then
    echo '<!--'
elif [[ "$2" = 'c' ]]; then
    echo '/*'
fi

while read -r line; do
    if [[ "$2" = 'sh' ]]; then
        echo -n "# "
    elif [[ "$2" = 'xml' ]]; then
        echo -n "    "
    elif [[ "$2" = 'c' ]]; then
        echo -n " * "
    fi

    if [[ "$line" = "http://www.apache.org/licenses/LICENSE-2.0" ]]; then
        echo -n "    "
    fi

    echo "$line"
done < <(__gen_apache $1)

if [[ "$2" = 'xml' ]]; then
    echo '-->'
elif [[ "$2" = 'c' ]]; then
    echo ' */'
fi
