#!/usr/bin/env dash
#
# My lemonbar setup.
# IMPORTANT:  This configuration is only compatible with
#             a lemonbar fork with xft font compatibility.
#

WRAPPER=$HOME/.bin/lemonbar_wrapper

# Check if the wrapper for this is compiled
if [ ! -f "$WRAPPER" ]; then
    cd $HOME/.bin
    gcc -lm -o lemonbar_wrapper lemonbar_wrapper.c
    cd -
fi

# Vertical size in percentage of the bar
BAR_HEIGHT_RATIO=04

# Find bspwm gap ratio
BSPWM_GAP=$(awk '/window_gap/{print $4}' $HOME/.config/bspwm/bspwmrc)
if [ $(echo $BSPWM | wc -l) -gt 1 ]; then BSPWM_GAP=0$BSPWM_GAP; fi

MONITOR_WIDTH=$(xrandr --query | grep ' connected' | grep -o '[0-9][0-9]\+' | sed -n 1p)
MONITOR_HEIGHT=$(xrandr --query | grep ' connected' | grep -o '[0-9][0-9]\+' | sed -n 2p)
BAR_WIDTH=$(echo "$MONITOR_WIDTH - $((BSPWM_GAP * 2))" | bc -l | sed 's/\..*//')
BAR_HEIGHT=$(echo "$MONITOR_HEIGHT * .$BAR_HEIGHT_RATIO" | bc -l | sed 's/\..*//')

FIFO=/tmp/lemonfifo
[ -e $FIFO ] && rm $FIFO
mkfifo $FIFO

# Check if `amixer` is available
command -v amixer && VOLUME_AVAILABLE=true

get_volume() {
    local slider
    local current_volume="$(amixer -D pulse get Master | awk -F'[][%]' 'END{print $2,$5}')"
    local is_muted=$(echo "$current_volume" | grep off)
    set -- $current_volume
    current_volume=$1
    local icon_array='  '

    set -- $icon_array

    if [ -n "$is_muted" ] || [ $current_volume = 0 ]; then
        glyph=$1
    elif [ $current_volume -le 50 ]; then
        glyph=$2
    else
        glyph=$3
    fi

    echo "get_volume$glyph  $($WRAPPER --build-slider $current_volume)"
}

seperate() {
    local items
    for i in "$@"; do
        [ -z "$i" ] && continue
        items="$items    |    $i"
    done
    echo "$items" | sed 's/ \+|//'
}

while :; do $WRAPPER --time; sleep 10; done > $FIFO &
while :; do $WRAPPER --used-memory-percentage; sleep 10; done > $FIFO &
while :; do $WRAPPER --bspwm-status; sleep .15; done > $FIFO &
while :; do $WRAPPER --network-status; sleep 10; done > $FIFO &
while :; do $WRAPPER --brightness-slider; sleep .6; done > $FIFO &
while :; do $WRAPPER --charge-glyph; sleep 2; done > $FIFO &

# Only run if amixer is available
if [ "$VOLUME_AVAILABLE" = true ]; then
    while :; do get_volume; sleep .6; done > $FIFO &
fi

while read -r line; do
    case $line in
        used-memory-percentage*)
            MEMORY_USAGE=$(echo "$line" | tail -c+23)
            ;;
        time*)
            TIME=$(echo "$line" | tail -c+5)
            ;;
        charge-glyph*)
            BATTERY=$(echo "$line" | tail -c+13)
            ;;
        bspwm-status*)
            BSPWM_STATUS=$(echo "$line" | tail -c+13)
            ;;
        network-status*)
            NETWORK_STATUS=$(echo "$line" | tail -c+15)
            ;;
        brightness-slider*)
            INTEL_BRIGHTNESS=$(echo "$line" | tail -c+18)
            ;;
        get_volume*)
            VOLUME=$(echo "$line" | tail -c+11)
            ;;
    esac
    echo "%{l}$(seperate "$TIME")%{c}$BSPWM_STATUS%{r}$(seperate "$VOLUME" "$INTEL_BRIGHTNESS" "$MEMORY_USAGE" "$NETWORK_STATUS" "$BATTERY")    "
done < $FIFO | lemonbar \
            -f 'Font Awesome 5 Free Solid:style=Solid' \
            -f 'SF Pro Display:style=Bold:size=10' \
            -g "$BAR_WIDTH"x"$BAR_HEIGHT"+"$BSPWM_GAP"+"$((BSPWM_GAP / 2))" \
            -B '#141b35' \
            -p | dash
