#!/usr/bin/env zsh
LC_ALL=C
LANG=C

# Make sure meminfo is compiled
if [[ ! -f $HOME/.bin/meminfo ]]; then
    cd $HOME/.bin
    gcc meminfo.c -o meminfo
    cd - &>/dev/null
fi

get_os() {
    OS=$(cat /etc/os-release | awk -F'"' '/^NAME/{print $2}')
}

get_host() {
    Host=$(cat /sys/devices/virtual/dmi/id/product_name)
}

get_kernel() {
    Kernel=$(uname -r)
}

get_packages() {
    Packages=$(pacman -Qsq | wc -l)
}

get_shell() {
    Shell=$($SHELL --version | sed 's/GNU //g; s/([^()]*)//g; s/-release//g; s/version//g; s/,//g; s/  / /g' \
        | head -n 1)
}

get_wm() {
    ID="$(xprop -root -notype _NET_SUPPORTING_WM_CHECK 2>/dev/null)"
    ID="${ID##* }"
    WM="$(xprop -id "$ID" -notype -len 100 -f _NET_WM_NAME 8t 2>/dev/null)"
    WM="${WM/*WM_NAME = }"
    WM="${WM/\"}"
    WM="${WM/\"*}"
}

get_terminal() {
    local tmp
    tmp=$(xdotool getactivewindow 2>/dev/null)
    tmp=$(xdotool getwindowpid $tmp 2>/dev/null)
    [[ -z $tmp ]] && return
    Terminal=$(perl -lpe 's/\0/ /g' /proc/$tmp/cmdline 2>/dev/null)
}

get_cpu_info() {
    MAX_GHZ=$(echo "$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq) / 1000000" \
        | bc -l | sed -n 's/00000000\+//p')
    CPU="$(echo "$(cat /proc/cpuinfo | awk -F': ' '/model name/{print $2}' | head -n 1 | sed 's/  / /g; s/(R)//g; s/ @.*//') @ ${MAX_GHZ}GHz")"
    GPU="$(lspci | sed -n 's/.*VGA compatible controller: //p' | sed -n 's/ (.*//p' | sed 's/ Integrated Graphics Controller//')"
    if [[ $(echo "$GPU" | wc -c) -gt 50 ]] && echo "$GPU" | grep -i processor | grep -i intel &>/dev/null; then
        GPU="Intel Integrated Graphics"
    fi
}

get_memory() {
    Memory="$(meminfo -u -m) / $(meminfo -t -m)"
}

get_uptime() {
    Uptime="$(uptime --pretty | sed 's/^up //')"
}

print_info() {
    if [[ -n "$1" ]]; then
        echo -e "$1"
    fi
}

get_os
get_host
get_kernel
get_packages
get_shell
get_wm
get_terminal
get_cpu_info
get_memory
get_uptime

for i in OS Host Kernel Packages Shell WM Terminal CPU GPU Memory Uptime; do
    eval tmp="\${$i}"
    if [[ $i == Host ]]; then
        if [[ $tmp = 'System Product Name' ]]; then
            continue
        fi
    elif [[ -z "$tmp" ]]; then
        continue
    fi
    LIST+=("\e[96m$i: \e[39m$tmp")
done

print_info "\e[96m$(whoami)\e[39m@\e[96m$(hostname)"
print_info "$LIST[1]"
print_info "$LIST[2]"
print_info "$LIST[3]"
print_info "$LIST[4]"
print_info "$LIST[5]"
print_info "$LIST[6]"
print_info "$LIST[7]"
print_info "$LIST[8]"
print_info "$LIST[9]"
print_info "$LIST[10]"
print_info "$LIST[11]"
print_info "$LIST[12]"
print_info "$LIST[13]"
print_info "$LIST[14]"
