#!/usr/bin/env bash

sudo modprobe -r elan_i2c
sudo modprobe elan_i2c
sleep .5
sudo xinput set-prop "Elan Touchpad" "libinput Middle Emulation Enabled" 1
sudo xinput set-prop "Elan Touchpad" "libinput Natural Scrolling Enabled" 1
sudo xinput set-prop "Elan Touchpad" "libinput Tapping Enabled" 1
