#!/usr/bin/env zsh

URL="https://api.telegram.org/bot$TGBOTTOKEN/sendMessage"
CHATIDS=(
    '499109275'
    '-1001247942938'
)

while [[ $# -gt 1 ]]; do
    case $1 in
        -p)
           shift
           case $1 in
               all)
                   CHATID+=" ${CHATIDS[@]}"
                   ;;
               pm)
                   CHATID+=" ${CHATIDS[1]}"
                   ;;
               nug)
                   CHATID+=" ${CHATIDS[2]}"
                   ;;
           esac
           ;;
        -m)
            shift
            MESSAGE="$1"
            ;;
    esac
shift
done

if [[ -z $MESSAGE ]]; then
    echo "You must specify a message!"
    exit 1
fi

if [[ -z $CHATID ]]; then
    echo "You must specify where to notify!"
    exit 1
fi

for i in $CHATID; do
    plc="$(echo $i | tr -d ' ')"
    curl -s -X POST $URL -d chat_id=$plc -d text="$MESSAGE" -d parse_mode="Markdown" &>/dev/null
    echo "Notified $plc"
done
