#!/usr/bin/env bash

URL="https://api.telegram.org/bot$TGBOTTOKEN/sendMessage"
CHATIDS=(
    '499109275'
    '-1001247942938'
    '-1001424244499'
)

while [[ $# -gt 1 ]]; do
    case $1 in
        -p)
           shift
           case $1 in
               all)
                   CHATID+=" ${CHATIDS[@]}"
                   ;;
               pm)
                   CHATID+=" ${CHATIDS[0]}"
                   ;;
               nug)
                   CHATID+=" ${CHATIDS[1]}"
                   ;;
               au)
                   CHATID+=" ${CHATIDS[2]}"
                   ;;
           esac
           ;;
        -m)
            shift
            MESSAGE="$1"
            ;;
        -c)
            CRABRAVE=true
            ;;
    esac
shift
done

if [[ -z $MESSAGE ]]; then
    echo "You must specify a message!"
    exit 1
fi

if [[ -z $CHATID ]]; then
    echo "You must specify where to notify!"
    exit 1
fi

set -x
if [[ -n $CRABRAVE ]]; then
    MESSAGE=$(
        NUM=${#MESSAGE}
        printf "%0.s🦀" $(seq $NUM)
        echo "%0A  $MESSAGE  "
        printf "%0.s🦀" $(seq $NUM)
    )
fi
set +x

for i in $CHATID; do
    curl -s -X POST $URL -d chat_id=$i -d text="$MESSAGE" -d parse_mode="Markdown" &>/dev/null
    echo "Notified $i"
done
