#!/usr/bin/env bash

unset TOTAL

START=$(date +%s)
$@
END=$(date +%s)
DIFF=$((END - START))
HOURS=$((DIFF / 3600))
MINS=$(((DIFF % 3600) / 60))
SECS=$((DIFF % 60))
if [[ $HOURS > 0 ]]; then
    TOTAL+="${HOURS}h "
fi
if [[ $MINS > 0 ]]; then
    TOTAL+="${MINS}m "
fi
if [[ $SECS > 0 ]]; then
    TOTAL+="${SECS}s"
fi
echo "$TOTAL"
export TIMER_TOTAL="$TOTAL"
