#!/usr/bin/env zsh

SCRIPT=$(realpath $0)
exec 6< $SCRIPT
flock -n 6 || exit

VOLUME_STEPS=5

if [[ $1 = -mute ]]; then
    NEW_VOLUME=$(amixer -D pulse sset Master toggle)
else
    NEW_VOLUME=$(amixer -D pulse sset Master $VOLUME_STEPS%$1)
fi

echo "$NEW_VOLUME" | grep -q off && MUTED=true
NEW_VOLUME=$(awk -F'[][%]' 'END{print $2}' <<< $NEW_VOLUME)

# Will be written to temp file for status bar
BAR_VOLUME=$NEW_VOLUME

[[ "$MUTED" = true ]] && BAR_VOLUME+="M"

printf '%s' "$BAR_VOLUME" > $HOME/.cache/volume/percentage
