#!/usr/bin/env zsh

LOCK=/tmp/volume_notify.lock

if [[ -f $LOCK ]]; then
    exit
fi
touch $LOCK

VOLUME_STEPS=5

if [[ $1 = -mute ]]; then
    if amixer -D pulse sset Master toggle | grep off; then
        NEW_VOLUME=Muted
    else
        NEW_VOLUME=$(amixer -D pulse get Master | awk -F'[][%]' 'END{print $2}')
    fi
else
    NEW_VOLUME=$(amixer -D pulse sset Master $VOLUME_STEPS%$1 | awk -F'[][%]' 'END{print $2}')
fi

if [[ $NEW_VOLUME = Muted || $NEW_VOLUME = 0 ]]; then
    ICON=notification-audio-volume-muted.svg
elif [[ $NEW_VOLUME -le 33 ]]; then
    ICON=notification-audio-volume-low.svg
elif [[ $NEW_VOLUME -le 66 ]]; then
    ICON=notification-audio-volume-medium.svg
else
    ICON=notification-audio-volume-high.svg
fi

if [[ $NEW_VOLUME != Muted ]]; then
    NEW_VOLUME+=%
fi

notify-send.sh --icon=/usr/share/icons/Numix/48/notifications/$ICON \
                --app-name="Volume Script" -R /tmp/volume_notify "Volume: $NEW_VOLUME"

rm $LOCK
