#!/usr/bin/env zsh

SCRIPT=$(realpath $0)
exec 6< $SCRIPT
flock -n 6 || exit

VOLUME_STEPS=5


if [[ $1 = -mute ]]; then
    amixer -D pulse sset Master toggle
    NEW_VOLUME=$(amixer -D pulse get Master | awk -F'[][%]' 'END{print $2}')
else
    NEW_VOLUME=$(amixer -D pulse sset Master $VOLUME_STEPS%$1 | awk -F'[][%]' 'END{print $2}')
fi

amixer -D pulse get Master | grep -q off && MUTED=true

if [[ -n $MUTED || $NEW_VOLUME = 0 ]]; then
    ICON=notification-audio-volume-muted.svg
elif [[ $NEW_VOLUME -le 33 ]]; then
    ICON=notification-audio-volume-low.svg
elif [[ $NEW_VOLUME -le 66 ]]; then
    ICON=notification-audio-volume-medium.svg
else
    ICON=notification-audio-volume-high.svg
fi

[[ -z "$MUTED" ]] && NEW_VOLUME+=% || NEW_VOLUME+="% (muted)"

notify-send.sh --icon=/usr/share/icons/Numix/48/notifications/$ICON "$NEW_VOLUME" \
        -R /tmp/volume_notify
