#!/bin/sh

sleep 6 && sxhkd &
compton &
dunst &
kill $(ps -xe | awk '/lemon/{print $1}'); $HOME/.bin/lemonbar_wrapper &
nitrogen --restore

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          20

bspc config split_ratio          0.5

bspc rule -a Google-chrome-unstable desktop='^2'
bspc rule -a Alacritty desktop='^1'
bspc rule -a TelegramDesktop desktop='^3'
