#!/bin/sh

sleep 3 && sxhkd &
compton &
dunst &
kill $(ps -xe | awk '/lemon/{print $1}'); $HOME/.bin/lemonbar_wrapper &
sleep 2; xdo above -t $(xdo id -n root) $(xdo id -n lemonbar) &
nitrogen --restore

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          40

bspc config split_ratio          0.5
bspc config gapless_monocle      false

bspc rule -a Google-chrome-unstable desktop='^2'
bspc rule -a Alacritty desktop='^1'
bspc rule -a TelegramDesktop desktop='^3'
