#!/usr/bin/env sh

pkill sxhkd
pkill picom
pkill twmnd

sxhkd &
twmnd &
nitrogen --set-scaled $HOME/.walls/pinkish-mountain.png &
picom --experimental-backends &
xrandr --output eDP-1 --mode 1600x900 &
for mf in 'Middle Emulation' 'Natural Scrolling' 'Tapping'; do
    xinput set-prop "Elan Touchpad" "libinput $mf Enabled" 1 &
done &
xsetroot -cursor_name top_left_arrow &

bspc monitor -d I II III IV V VI &

bspc config border_width 0 &
bspc config window_gap 20 &
bspc config split_ratio 0.5 &
bspc config border_radius 7 &
