#!/usr/bin/env bash

# Dependencies: pacman-contrib

UPDATES=$(checkupdates)

UPDATES_NUM=$(echo -n ${UPDATES[@]} | wc -l)

if [[ ${UPDATES_NUM} != 0 ]]; then
    if [[ ${1} = "-n" ]]; then
        echo " ${UPDATES_NUM}"
    elif [[ ${1} = "-u" ]]; then
        notify-send.sh --app-name="Pacman updates" "${UPDATES[@]}"
    fi
fi
