#!/usr/bin/env bash

# checkupdates depends on pacman-contrib
ARCH=$(checkupdates | wc -l 2>/dev/null) || exit 1
AUR=$(pakku -Qum | wc -l 2>/dev/null) || exit 1
UPDATES=$((ARCH + AUR))
echo ${UPDATES}
